/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.kalkulator;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author Michał_pc
 */
public class kalkulator extends javax.swing.JFrame {

    private DateTimeFormatter DateTimeFormatter;
    private DateTimeFormatter formatter;
    private CharSequence date;

    /**
     * Creates new form kalkulator
     */
    public kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        mz_jButton8 = new javax.swing.JButton();
        mz_jButton9 = new javax.swing.JButton();
        mz_jButton7 = new javax.swing.JButton();
        mz_jButton4 = new javax.swing.JButton();
        mz_jButtonX = new javax.swing.JButton();
        mz_jButton6 = new javax.swing.JButton();
        mz_jButtonMinus = new javax.swing.JButton();
        mz_jButton5 = new javax.swing.JButton();
        mz_jButton1 = new javax.swing.JButton();
        mz_jButton2 = new javax.swing.JButton();
        mz_jButton3 = new javax.swing.JButton();
        mz_jButtonPlus = new javax.swing.JButton();
        mz_jButtonDzielenie = new javax.swing.JButton();
        mz_jButton0 = new javax.swing.JButton();
        mz_jButtonPrzecinek = new javax.swing.JButton();
        mz_jButtonKoniec = new javax.swing.JButton();
        mz_jTextField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuTools = new javax.swing.JMenu();
        jMenuDniMiedzyDatami = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMain.setBackground(new java.awt.Color(51, 0, 51));

        mz_jButton8.setText("8");
        mz_jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mz_jButton8ActionPerformed(evt);
            }
        });

        mz_jButton9.setText("9");
        mz_jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mz_jButton9ActionPerformed(evt);
            }
        });

        mz_jButton7.setText("7");
        mz_jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mz_jButton7ActionPerformed(evt);
            }
        });

        mz_jButton4.setText("4");
        mz_jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mz_jButton4ActionPerformed(evt);
            }
        });

        mz_jButtonX.setText("x");

        mz_jButton6.setText("6");
        mz_jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mz_jButton6ActionPerformed(evt);
            }
        });

        mz_jButtonMinus.setText("-");
        mz_jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mz_jButtonMinusActionPerformed(evt);
            }
        });

        mz_jButton5.setText("5");
        mz_jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mz_jButton5ActionPerformed(evt);
            }
        });

        mz_jButton1.setText("1");
        mz_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mz_jButton1ActionPerformed(evt);
            }
        });

        mz_jButton2.setText("2");
        mz_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mz_jButton2ActionPerformed(evt);
            }
        });

        mz_jButton3.setText("3");
        mz_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mz_jButton3ActionPerformed(evt);
            }
        });

        mz_jButtonPlus.setText("+");
        mz_jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mz_jButtonPlusActionPerformed(evt);
            }
        });

        mz_jButtonDzielenie.setText("/");

        mz_jButton0.setText("0");
        mz_jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mz_jButton0ActionPerformed(evt);
            }
        });

        mz_jButtonPrzecinek.setText(",");

        mz_jButtonKoniec.setText("=");
        mz_jButtonKoniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mz_jButtonKoniecActionPerformed(evt);
            }
        });

        mz_jTextField.setEditable(false);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mz_jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mz_jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mz_jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mz_jButtonKoniec, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mz_jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(mz_jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mz_jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mz_jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mz_jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(mz_jButton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mz_jButtonPrzecinek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mz_jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mz_jButtonPlus, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(mz_jButtonDzielenie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mz_jButtonMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mz_jButtonX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mz_jTextField)
                .addContainerGap())
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mz_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mz_jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mz_jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mz_jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mz_jButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mz_jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mz_jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mz_jButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mz_jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mz_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mz_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mz_jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mz_jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mz_jButtonDzielenie, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mz_jButtonPrzecinek, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mz_jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mz_jButtonKoniec, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jMenuFile.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItem1);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Edit");
        jMenuBar1.add(jMenuEdit);

        jMenuTools.setText("Tools");

        jMenuDniMiedzyDatami.setText("Daty");
        jMenuDniMiedzyDatami.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDniMiedzyDatamiActionPerformed(evt);
            }
        });
        jMenuTools.add(jMenuDniMiedzyDatami);

        jMenuBar1.add(jMenuTools);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String liczba = "";
    private void mz_jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mz_jButton0ActionPerformed
        mz_jTextField.setText(liczba+"0");
        liczba=mz_jTextField.getText();
    }//GEN-LAST:event_mz_jButton0ActionPerformed

    private void mz_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mz_jButton1ActionPerformed
        mz_jTextField.setText(liczba+"1");
        liczba=mz_jTextField.getText();
    }//GEN-LAST:event_mz_jButton1ActionPerformed

    private void mz_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mz_jButton2ActionPerformed
        mz_jTextField.setText(liczba+"2");
        liczba=mz_jTextField.getText();
    }//GEN-LAST:event_mz_jButton2ActionPerformed

    private void mz_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mz_jButton3ActionPerformed
        mz_jTextField.setText(liczba+"3");
        liczba=mz_jTextField.getText();
    }//GEN-LAST:event_mz_jButton3ActionPerformed

    private void mz_jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mz_jButton4ActionPerformed
        mz_jTextField.setText(liczba+"4");
        liczba=mz_jTextField.getText();
    }//GEN-LAST:event_mz_jButton4ActionPerformed

    private void mz_jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mz_jButton5ActionPerformed
        mz_jTextField.setText(liczba+"5");
        liczba=mz_jTextField.getText();
    }//GEN-LAST:event_mz_jButton5ActionPerformed

    private void mz_jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mz_jButton6ActionPerformed
        mz_jTextField.setText(liczba+"6");
        liczba=mz_jTextField.getText();
    }//GEN-LAST:event_mz_jButton6ActionPerformed

    private void mz_jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mz_jButton7ActionPerformed
        mz_jTextField.setText(liczba+"7");
        liczba=mz_jTextField.getText();
    }//GEN-LAST:event_mz_jButton7ActionPerformed

    private void mz_jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mz_jButton8ActionPerformed
        mz_jTextField.setText(liczba+"8");
        liczba=mz_jTextField.getText();
    }//GEN-LAST:event_mz_jButton8ActionPerformed

    private void mz_jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mz_jButton9ActionPerformed
        mz_jTextField.setText(liczba+"9");
        liczba=mz_jTextField.getText();
    }//GEN-LAST:event_mz_jButton9ActionPerformed
    int liczba1;
    int liczba2;
    String sign = "";
    
    private void mz_jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mz_jButtonPlusActionPerformed
        sign = "+";
        liczba1 = Integer.parseInt(liczba);
        liczba ="";
    }//GEN-LAST:event_mz_jButtonPlusActionPerformed

    private void mz_jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mz_jButtonMinusActionPerformed
        sign = "-";
        liczba1 = Integer.parseInt(liczba);
        liczba ="";
    }//GEN-LAST:event_mz_jButtonMinusActionPerformed

    private void mz_jButtonKoniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mz_jButtonKoniecActionPerformed
        liczba2 = Integer.parseInt(liczba);
        if(sign.equals("+")){
            int wynik = liczba1 + liczba2;
            String tekst = String.valueOf(wynik);
            mz_jTextField.setText(tekst);
            liczba = "";
        }else if(sign.equals("-")){
            int wynik = liczba1 - liczba2;
            String tekst = String.valueOf(wynik);
            mz_jTextField.setText(tekst);
            liczba = "";
        }
    }//GEN-LAST:event_mz_jButtonKoniecActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuDniMiedzyDatamiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDniMiedzyDatamiActionPerformed
        // narzedzie pozwalajace na zamiane wprowadzonego tekstu na date
        DateTimeFormatter = DateTimeFormatter.ofPattern("dd MM yyyy");
        String data = JOptionPane.showInputDialog("Wprowadz date w formacie dd mm yyyy np: 01 02 2021");
        //System.out.println(data);
        if(data != null && data.length()>1){
        LocalDate DateNow = LocalDate.now();
        LocalDate DateInput = LocalDate.parse(data, formatter); // zrobienie LocalDate z tekstu dzieki formatter
        //System.out.println(DateNow+" "+DateInput);
        long days = ChronoUnit.DAYS.between(DateInput, DateNow);
        //System.out.println("Ilosc dni miedzy datami"+days);
        
        }
    }//GEN-LAST:event_jMenuDniMiedzyDatamiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDniMiedzyDatami;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JButton mz_jButton0;
    private javax.swing.JButton mz_jButton1;
    private javax.swing.JButton mz_jButton2;
    private javax.swing.JButton mz_jButton3;
    private javax.swing.JButton mz_jButton4;
    private javax.swing.JButton mz_jButton5;
    private javax.swing.JButton mz_jButton6;
    private javax.swing.JButton mz_jButton7;
    private javax.swing.JButton mz_jButton8;
    private javax.swing.JButton mz_jButton9;
    private javax.swing.JButton mz_jButtonDzielenie;
    private javax.swing.JButton mz_jButtonKoniec;
    private javax.swing.JButton mz_jButtonMinus;
    private javax.swing.JButton mz_jButtonPlus;
    private javax.swing.JButton mz_jButtonPrzecinek;
    private javax.swing.JButton mz_jButtonX;
    private javax.swing.JTextField mz_jTextField;
    // End of variables declaration//GEN-END:variables
}
