/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zuterek.Listazakupow1;

/**
 *
 * @author Michał_pc
 */
public class ListaZakupow1 extends javax.swing.JFrame {

    /**
     * Creates new form ListaZakupow1
     */
    public ListaZakupow1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jTabbedPaneMain = new javax.swing.JTabbedPane();
        jToolBarWprowadz = new javax.swing.JToolBar();
        jPanelWprowadz = new javax.swing.JPanel();
        jLabelWpisz = new javax.swing.JLabel();
        jTextFieldWpisz = new javax.swing.JTextField();
        jLabelWartosc = new javax.swing.JLabel();
        jTextFieldWartosc = new javax.swing.JTextField();
        jComboBoxTowar = new javax.swing.JComboBox<>();
        jLabelTowar = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jButtonZapisz = new javax.swing.JButton();
        jLabelDzisiejsze = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jLabelWydatki1 = new javax.swing.JLabel();
        jTextFieldWydatki1 = new javax.swing.JTextField();
        jLabelWydatki2 = new javax.swing.JLabel();
        jTextFieldWydatki2 = new javax.swing.JTextField();
        jToolBarLista = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBarWprowadz.setRollover(true);

        jLabelWpisz.setText("Wpisz co kupiłeś: ");

        jLabelWartosc.setText("Podaj wartosc");

        jComboBoxTowar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelTowar.setText("Typ zakupionego towaru");

        jLabelData.setText("Data");

        jButtonZapisz.setText("zapisz");

        jLabelDzisiejsze.setText("Dzisiejsze zakupy");

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        jLabelWydatki1.setText("Wydatki z dzisiaj");

        jLabelWydatki2.setText("Wydatki z tygodnia");

        javax.swing.GroupLayout jPanelWprowadzLayout = new javax.swing.GroupLayout(jPanelWprowadz);
        jPanelWprowadz.setLayout(jPanelWprowadzLayout);
        jPanelWprowadzLayout.setHorizontalGroup(
            jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWprowadzLayout.createSequentialGroup()
                .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDzisiejsze, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelWprowadzLayout.createSequentialGroup()
                        .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelWprowadzLayout.createSequentialGroup()
                                .addComponent(jLabelWpisz, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(jLabelWartosc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelWprowadzLayout.createSequentialGroup()
                                .addComponent(jTextFieldWpisz, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldWartosc)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelWprowadzLayout.createSequentialGroup()
                                .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxTowar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTowar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelData)
                                    .addComponent(jTextFieldData)
                                    .addComponent(jButtonZapisz, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                .addGap(0, 26, Short.MAX_VALUE))
                            .addGroup(jPanelWprowadzLayout.createSequentialGroup()
                                .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelWydatki1)
                                    .addComponent(jLabelWydatki2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldWydatki2)
                                    .addComponent(jTextFieldWydatki1))))))
                .addContainerGap())
        );
        jPanelWprowadzLayout.setVerticalGroup(
            jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWprowadzLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWpisz)
                    .addComponent(jLabelWartosc)
                    .addComponent(jLabelTowar)
                    .addComponent(jLabelData))
                .addGap(18, 18, 18)
                .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldWpisz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldWartosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTowar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonZapisz)
                .addGap(18, 18, 18)
                .addComponent(jLabelDzisiejsze)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelWprowadzLayout.createSequentialGroup()
                        .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelWydatki1)
                            .addComponent(jTextFieldWydatki1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelWprowadzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelWydatki2)
                            .addComponent(jTextFieldWydatki2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBarWprowadz.add(jPanelWprowadz);

        jTabbedPaneMain.addTab("Wprowadzanie zakupow", jToolBarWprowadz);

        jToolBarLista.setRollover(true);
        jTabbedPaneMain.addTab("Lista zakupow", jToolBarLista);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMain)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMain)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaZakupow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaZakupow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaZakupow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaZakupow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaZakupow1().setVisible(true);
            }
        });
    }
     
    private void addTooltipToElements(){
        jTextFieldWpisz.setToolTipText("<html>"
                +"<h3>Wprowadz tekst</h3>"
                +"<p>Nie uzywaj polskich znakow</p>"
                +"</html>");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonZapisz;
    private javax.swing.JComboBox<String> jComboBoxTowar;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDzisiejsze;
    private javax.swing.JLabel jLabelTowar;
    private javax.swing.JLabel jLabelWartosc;
    private javax.swing.JLabel jLabelWpisz;
    private javax.swing.JLabel jLabelWydatki1;
    private javax.swing.JLabel jLabelWydatki2;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelWprowadz;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneMain;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldWartosc;
    private javax.swing.JTextField jTextFieldWpisz;
    private javax.swing.JTextField jTextFieldWydatki1;
    private javax.swing.JTextField jTextFieldWydatki2;
    private javax.swing.JToolBar jToolBarLista;
    private javax.swing.JToolBar jToolBarWprowadz;
    // End of variables declaration//GEN-END:variables
}
