/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.zuterekm;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.*;
/**
 *
 * @author Michał_pc
 */
public class zuterekm extends javax.swing.JFrame {

    /**
     * Creates new form zuterekm
     */
    public zuterekm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mz_jPanelMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxWybor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldWprowadzona = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPrzeliczona = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaHistoria = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        Files = new javax.swing.JMenu();
        jMenuItemHistoria = new javax.swing.JMenuItem();
        jMenuItemexit = new javax.swing.JMenuItem();
        Info = new javax.swing.JMenu();
        jMenuIteminfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mz_jPanelMain.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Co zamierzasz przeliczyć??");

        jComboBoxWybor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jComboBoxWybor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Temperatura", "Odległość" }));
        jComboBoxWybor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxWyborActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Wprowadź wartość:");

        jTextFieldWprowadzona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWprowadzonaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Przeliczona wartość:");

        jTextAreaHistoria.setColumns(20);
        jTextAreaHistoria.setRows(5);
        jScrollPane1.setViewportView(jTextAreaHistoria);

        javax.swing.GroupLayout mz_jPanelMainLayout = new javax.swing.GroupLayout(mz_jPanelMain);
        mz_jPanelMain.setLayout(mz_jPanelMainLayout);
        mz_jPanelMainLayout.setHorizontalGroup(
            mz_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mz_jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mz_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(mz_jPanelMainLayout.createSequentialGroup()
                        .addGroup(mz_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mz_jPanelMainLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxWybor, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mz_jPanelMainLayout.createSequentialGroup()
                                .addGroup(mz_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mz_jPanelMainLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(mz_jPanelMainLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(15, 15, 15)))
                                .addGroup(mz_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldWprowadzona)
                                    .addComponent(jTextFieldPrzeliczona, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))))
                        .addGap(0, 167, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mz_jPanelMainLayout.setVerticalGroup(
            mz_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mz_jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mz_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxWybor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(mz_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldWprowadzona))
                .addGap(18, 18, 18)
                .addGroup(mz_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldPrzeliczona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Files.setText("File");

        jMenuItemHistoria.setText("Historia");
        jMenuItemHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHistoriaActionPerformed(evt);
            }
        });
        Files.add(jMenuItemHistoria);

        jMenuItemexit.setText("Exit");
        jMenuItemexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemexitActionPerformed(evt);
            }
        });
        Files.add(jMenuItemexit);

        jMenuBar1.add(Files);

        Info.setText("Info");

        jMenuIteminfo.setText("info");
        Info.add(jMenuIteminfo);

        jMenuBar1.add(Info);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mz_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mz_jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemexitActionPerformed

    private void jComboBoxWyborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxWyborActionPerformed
        String jednostka = (String) jComboBoxWybor.getSelectedItem();
        if(jednostka.equals("Temperatura")){
            jLabel2.setText("Wprowadź wartość (kelwiny): ");
        }else{
            jLabel2.setText("Wprowadź wartość (metry): ");
        }
        if(jednostka.equals("Temperatura")){
            jLabel3.setText("Przeliczona wartość (stopnie Celsjusza): ");
        }else{
            jLabel3.setText("Przeliczona wartość (kilometry): ");
        }
                                 
    }//GEN-LAST:event_jComboBoxWyborActionPerformed

    private void jTextFieldWprowadzonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWprowadzonaActionPerformed
        String dane =("");
        String jednostka = (String) jComboBoxWybor.getSelectedItem();
        if(jednostka.equals("Temperatura")){
            String wpisane = jTextFieldPrzeliczona.getText();
            int kelwiny = Integer.parseInt(wpisane);
            double celsjusze = kelwiny-273;
            String tekst =String.valueOf(celsjusze);
            
            jTextFieldWprowadzona.setText(tekst);
            dane = "t;k= "+kelwiny+";c= "+celsjusze;
        }else{
            String wpisane = jTextFieldPrzeliczona.getText();
            double metry = Integer.parseInt(wpisane);
            double kilometry = metry/1000;
            String tekst =String.valueOf(kilometry);
            
            jTextFieldWprowadzona.setText(tekst);
            dane = "o;m= "+metry+";km= "+kilometry+"\n";
        }  
        
         File f = new File("przeliczanie.txt");
        try{
            FileWriter fw = new FileWriter(f,true);
            fw.write(dane+"\n");
            fw.close();
        } catch(IOException e){
            System.out.println("błąd: "+e.toString());
        }
    }//GEN-LAST:event_jTextFieldWprowadzonaActionPerformed

    private void jMenuItemHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHistoriaActionPerformed
        JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showDialog(this,"Wybierz plik");

        try {
            String text ="";
            File f = jFileChooser.getSelectedFile();
            Scanner sc = new Scanner(f);
            while(sc.hasNext()){
                text = text+sc.nextLine()+"\n";
            }
            jTextAreaHistoria.setText(text);
        }catch (FileNotFoundException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_jMenuItemHistoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(zuterekm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(zuterekm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(zuterekm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(zuterekm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new zuterekm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Files;
    private javax.swing.JMenu Info;
    private javax.swing.JComboBox<String> jComboBoxWybor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemHistoria;
    private javax.swing.JMenuItem jMenuItemexit;
    private javax.swing.JMenuItem jMenuIteminfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaHistoria;
    private javax.swing.JTextField jTextFieldPrzeliczona;
    private javax.swing.JTextField jTextFieldWprowadzona;
    private javax.swing.JPanel mz_jPanelMain;
    // End of variables declaration//GEN-END:variables
}
