/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zuterek.kolkoandkrzyzyk;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import zuterek.kolkoandkrzyzyk.gameutils.DrawPlayer;

/**
 *
 * @author Michał_pc
 */
public class GameWindow extends javax.swing.JFrame {
    private boolean sign = false;
    private boolean player = false;

    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        initComponents();
        initGame();
        setCircleOrCrossToAllButtons();
        clearButtonText();
    }

    private void initGame(){
        player = DrawPlayer.randomPlayer();
        sign = DrawPlayer.randomPlayer();
        if(player){
            jLGracz1.setBackground(Color.GREEN);
            jLGracz2.setBackground(Color.BLUE);
        }else{
            jLGracz2.setBackground(Color.GREEN);
            jLGracz1.setBackground(Color.BLUE);
        }
        if(sign){
            jLZnakGracza1.setText("O");
            jLZnakGracza2.setText("X");
        }else{
            jLZnakGracza1.setText("X");
            jLZnakGracza2.setText("O");
        }
    }
    
    private void setCircleOrCrossToAllButtons(){
        jButtonA1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
               setCircleOrCross(evt);
            }
        });
        
        jButtonA2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
               setCircleOrCross(evt);
            }
        });
        
        jButtonA3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
               setCircleOrCross(evt);
            }
        });
        
        jButtonB1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
               setCircleOrCross(evt);
            }
        });
        
        jButtonB2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
               setCircleOrCross(evt);
            }
        });
        
        jButtonB3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
               setCircleOrCross(evt);
            }
        });
        
        jButtonC1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
               setCircleOrCross(evt);
            }
        });
        
        jButtonC2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
               setCircleOrCross(evt);
            }
        });
        
        jButtonC3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
               setCircleOrCross(evt);
            }
        });
    }
    
    private void clearButtonText(){
        jButtonA1.setText("");
        jButtonA2.setText("");
        jButtonA3.setText("");
        jButtonB1.setText("");
        jButtonB2.setText("");
        jButtonB3.setText("");
        jButtonC1.setText("");
        jButtonC2.setText("");
        jButtonC3.setText("");
        
    }
    
    private void setCircleOrCross(java.awt.event.ActionEvent evt){
        JButton b = (JButton)evt.getSource();
        if(sign){
            b.setText("X");
        }else{
            b.setText("O");
        }
        sign = !sign;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRBGraczVsGracz = new javax.swing.JRadioButton();
        jRBGraczVsBot = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLGracz1 = new javax.swing.JLabel();
        jLGracz2 = new javax.swing.JLabel();
        jLZnakGracza1 = new javax.swing.JLabel();
        jLZnakGracza2 = new javax.swing.JLabel();
        jBReset = new javax.swing.JButton();
        jButtonA3 = new javax.swing.JButton();
        jButtonA2 = new javax.swing.JButton();
        jButtonA1 = new javax.swing.JButton();
        jButtonC1 = new javax.swing.JButton();
        jButtonC2 = new javax.swing.JButton();
        jButtonC3 = new javax.swing.JButton();
        jButtonB1 = new javax.swing.JButton();
        jButtonB2 = new javax.swing.JButton();
        jButtonB3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRBGraczVsGracz);
        jRBGraczVsGracz.setSelected(true);
        jRBGraczVsGracz.setText("Gracz VS Gracz");

        buttonGroup1.add(jRBGraczVsBot);
        jRBGraczVsBot.setText("Gracz VS Bot");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLGracz1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLGracz1.setText("Gracz 1");
        jLGracz1.setOpaque(true);

        jLGracz2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLGracz2.setText("Gracz 2");
        jLGracz2.setOpaque(true);

        jLZnakGracza1.setText("X");

        jLZnakGracza2.setText("O");

        jBReset.setText("RESET");
        jBReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBResetActionPerformed(evt);
            }
        });

        jButtonA3.setMaximumSize(new java.awt.Dimension(60, 60));
        jButtonA3.setMinimumSize(new java.awt.Dimension(60, 60));

        jButtonA2.setMaximumSize(new java.awt.Dimension(60, 60));
        jButtonA2.setMinimumSize(new java.awt.Dimension(60, 60));

        jButtonA1.setMaximumSize(new java.awt.Dimension(60, 60));
        jButtonA1.setMinimumSize(new java.awt.Dimension(60, 60));

        jButtonC1.setMaximumSize(new java.awt.Dimension(60, 60));
        jButtonC1.setMinimumSize(new java.awt.Dimension(60, 60));
        jButtonC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonC1ActionPerformed(evt);
            }
        });

        jButtonC2.setMaximumSize(new java.awt.Dimension(60, 60));
        jButtonC2.setMinimumSize(new java.awt.Dimension(60, 60));
        jButtonC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonC2ActionPerformed(evt);
            }
        });

        jButtonB1.setMaximumSize(new java.awt.Dimension(60, 60));
        jButtonB1.setMinimumSize(new java.awt.Dimension(60, 60));
        jButtonB1.setPreferredSize(new java.awt.Dimension(60, 60));

        jButtonB2.setMaximumSize(new java.awt.Dimension(60, 60));
        jButtonB2.setMinimumSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLGracz1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLZnakGracza1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButtonA3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(jButtonA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonA1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButtonB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonC1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(jButtonC2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonC3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRBGraczVsGracz)
                        .addGap(18, 18, 18)
                        .addComponent(jRBGraczVsBot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBReset, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLZnakGracza2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jLGracz2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBGraczVsGracz)
                    .addComponent(jRBGraczVsBot)
                    .addComponent(jBReset))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLZnakGracza1)
                    .addComponent(jLZnakGracza2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLGracz1)
                    .addComponent(jLGracz2))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonC2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jButtonB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonC3, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jButtonA3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jBResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBResetActionPerformed
        initGame();
        clearButtonText();
    }//GEN-LAST:event_jBResetActionPerformed

    private void jButtonC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonC2ActionPerformed

    private void jButtonC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonC1ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBReset;
    private javax.swing.JButton jButtonA1;
    private javax.swing.JButton jButtonA2;
    private javax.swing.JButton jButtonA3;
    private javax.swing.JButton jButtonB1;
    private javax.swing.JButton jButtonB2;
    private javax.swing.JButton jButtonB3;
    private javax.swing.JButton jButtonC1;
    private javax.swing.JButton jButtonC2;
    private javax.swing.JButton jButtonC3;
    private javax.swing.JLabel jLGracz1;
    private javax.swing.JLabel jLGracz2;
    private javax.swing.JLabel jLZnakGracza1;
    private javax.swing.JLabel jLZnakGracza2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBGraczVsBot;
    private javax.swing.JRadioButton jRBGraczVsGracz;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
