/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.przeliczanie;

/**
 *
 * @author Michał_pc
 */
public class Przeliczanie extends javax.swing.JFrame {

    /**
     * Creates new form Przeliczanie
     */
    public Przeliczanie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLabelPrzeliczanie = new javax.swing.JLabel();
        jComboBoxPrzeliczanie = new javax.swing.JComboBox<>();
        jLabelJednostki = new javax.swing.JLabel();
        jLabelPrzeliczone = new javax.swing.JLabel();
        jTextFieldJednostka = new javax.swing.JTextField();
        jTextFieldPrzeliczone = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemEXIT = new javax.swing.JMenuItem();
        jMenuItemHISOTRIA = new javax.swing.JMenuItem();
        jMenuInfo = new javax.swing.JMenu();
        jMenuItemInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMain.setBackground(new java.awt.Color(102, 102, 255));

        jLabelPrzeliczanie.setText("CO CHCESZ PRZELICZYC?");

        jComboBoxPrzeliczanie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Temperatura", "Odleglosc" }));
        jComboBoxPrzeliczanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPrzeliczanieActionPerformed(evt);
            }
        });

        jLabelJednostki.setText("WPROWADZ WARTOSC ; ");

        jLabelPrzeliczone.setText("WYNIK ;");

        jTextFieldJednostka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJednostkaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabelPrzeliczanie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxPrzeliczanie, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabelJednostki)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldJednostka, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabelPrzeliczone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPrzeliczone, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPrzeliczanie)
                    .addComponent(jComboBoxPrzeliczanie, javax.swing.GroupLayout.PREFERRED_SIZE, 19, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJednostki)
                    .addComponent(jTextFieldJednostka, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPrzeliczone)
                    .addComponent(jTextFieldPrzeliczone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        jMenuFile.setText("File");

        jMenuItemEXIT.setText("EXIT");
        jMenuItemEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEXITActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemEXIT);

        jMenuItemHISOTRIA.setText("HISTORIA");
        jMenuFile.add(jMenuItemHISOTRIA);

        jMenuBar1.add(jMenuFile);

        jMenuInfo.setText("info");

        jMenuItemInfo.setText("INFO");
        jMenuInfo.add(jMenuItemInfo);

        jMenuBar1.add(jMenuInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemEXITActionPerformed

    private void jComboBoxPrzeliczanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPrzeliczanieActionPerformed
        String jednostka = (String) jComboBoxPrzeliczanie.getSelectedItem();
        if(jednostka.equals("Temperatura")){
            jLabelJednostki.setText("Wprowadź wartość (kelwiny): ");
        }else{
            jLabelJednostki.setText("Wprowadź wartość(metry): ");
        }
        if(jednostka.equals("Temperatura")){
            jLabelPrzeliczone.setText("Przeliczona wartość (stopnie Celsjusza): ");
        }else{
            jLabelPrzeliczone.setText("Przeliczona wartość (kilometry): ");
        }
    }//GEN-LAST:event_jComboBoxPrzeliczanieActionPerformed

    private void jTextFieldJednostkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJednostkaActionPerformed
        String dane =("");
        String jednostka = (String) jComboBoxPrzeliczanie.getSelectedItem();
        if(jednostka.equals("Temperatura")){
            String wpisane = jTextFieldJednostka.getText();
            int kelwiny = Integer.parseInt(wpisane);
            double celsjusze = kelwiny-273;
            String tekst =String.valueOf(celsjusze);
            
            jTextFieldPrzeliczone.setText(tekst);
            dane = "t;k= "+kelwiny+";c= "+celsjusze;
        }else{
            String wpisane = jTextFieldJednostka.getText();
            double metry = Integer.parseInt(wpisane);
            double kilometry = metry/1000;
            String tekst =String.valueOf(kilometry);
            
            jTextFieldPrzeliczone.setText(tekst);
            dane = "o;m= "+metry+";km= "+kilometry+"\n";
        }   
    }//GEN-LAST:event_jTextFieldJednostkaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Przeliczanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Przeliczanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Przeliczanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Przeliczanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Przeliczanie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxPrzeliczanie;
    private javax.swing.JLabel jLabelJednostki;
    private javax.swing.JLabel jLabelPrzeliczanie;
    private javax.swing.JLabel jLabelPrzeliczone;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuInfo;
    private javax.swing.JMenuItem jMenuItemEXIT;
    private javax.swing.JMenuItem jMenuItemHISOTRIA;
    private javax.swing.JMenuItem jMenuItemInfo;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JTextField jTextFieldJednostka;
    private javax.swing.JTextField jTextFieldPrzeliczone;
    // End of variables declaration//GEN-END:variables
}
